### ISSUE TITLE
Allow playlist creation based on metrics

### ISSUE THREAD

**Issue by cheshire137** [cheshire137/spotty-features#3]
Let the user specify things like "positive danceable tracks," "negative acoustic tracks," "live tracks with low energy," etc. and create a playlist for them of tracks they have saved that have those qualities.

Idea inspired by @tcbyrd!

**Comment by cheshire137** [comment]
Can use https://developer.spotify.com/web-api/get-recommendations/ with its `min_` and `max_` filters for acousticness, instrumentalness, etc.

**Comment by cheshire137** [comment]
Done!

**Comment by mikedillion** [comment]
Sarah, I love you.

**Comment by cheshire137** [comment]
Hehe, thanks Mike. 😍
